[ADD] estate: Linked business logic to action buttons to cancel, set as sold, accept, or refuse offers following Odoo Guide t#70762
Cindypsd/Odoo_Training pull request #3
Opened 2023-04-25 19:14 UTC by Cindypsd

Explanation:

Added buttons to cancel or set a property as sold, a canceled property cannot be sold and a sold property cannot be canceled, it should raise an error in any of these cases:

![Captura de Pantalla 2023-04-25 a la(s) 12 58 12](https://user-images.githubusercontent.com/108036643/234378088-badb9a3f-dae8-44c8-8c60-f15558608534.png)

Added a function  to accept or refuse an offer:
![Captura de Pantalla 2023-04-25 a la(s) 13 01 03](https://user-images.githubusercontent.com/108036643/234378370-1257feca-b689-417b-98df-99383a03dc5a.png)

Once an offer is accepted, the selling price and the buyer should be set:
![Captura de Pantalla 2023-04-25 a la(s) 13 12 32](https://user-images.githubusercontent.com/108036643/234379350-715fc0b0-b636-45b9-9ad2-9b4425fb5f94.png)

![Captura de Pantalla 2023-04-25 a la(s) 13 01 11](https://user-images.githubusercontent.com/108036643/234378637-fa0c485d-cbd7-42d1-bcec-b79852bcc411.png)

2023-04-25 19:52 UTC, sebasdrk17 requested changes

2023-04-25 19:52 UTC, sebasdrk17 commented on estate/models/estate_property.py
> +                raise exceptions.UserError("Property is already sold")
This is OK if we need specific error messages

another alternative could be this:

```py
if record.state in ["canceled", "sold"]:
    raise exceptions.UserError("A property with state %s cannot be changed to sold." % record.state)
```

2023-04-25 19:52 UTC, sebasdrk17 commented on estate/models/estate_property_offer.py
> +    buyer_id = fields.Many2one("res.partner")
no need for two fields, remove one please

2023-04-25 19:52 UTC, sebasdrk17 commented on estate/models/estate_property_offer.py
> +            if record.date_deadline:
if there is no `date_deadline` this is not going to do anything, is this expected?

2023-04-25 19:52 UTC, sebasdrk17 commented on estate/models/estate_property_offer.py
> +        return True
Duplicated method, remove one please

2023-04-25 23:45 UTC, Cindypsd commented
@sebasdrk17 

Requested changes made

2023-04-26 17:18 UTC, sebasdrk17 requested changes
Functional testing:

This warning triggers when loading the instance:

![Screenshot 2023-04-26 at 10 41 45 a m](https://user-images.githubusercontent.com/47955967/234645001-50d70892-fb93-4e8f-b88c-c2467126234c.png)

I found something weird, but tell me if that's how it's supposed to be:

https://user-images.githubusercontent.com/47955967/234649721-eda7b484-da8e-4ac0-b246-da65ec9e6d5d.mp4

2023-04-26 17:18 UTC, sebasdrk17 commented on estate/views/estate_property_views.xml
> +                                            attrs="{'invisible': [('status', 'in', ('accepted','refused'))]}"
Use a list instead of a tuple

```suggestion
                                            attrs="{'invisible': [('status', 'in', ['accepted','refused'])]}"
```

2023-04-26 17:18 UTC, sebasdrk17 commented on estate/views/estate_property_views.xml
> +                                            attrs="{'invisible': [('status', 'in', ('accepted','refused'))]}"
Use a list instead of a tuple

```suggestion
                                            attrs="{'invisible': [('status', 'in', ['accepted','refused'])]}"
```

2023-04-26 18:22 UTC, Cindypsd commented
@sebasdrk17 

I have made the necessary changes to remove the warnings. Additionally, I updated the function action_sold to ensure that when an offer is accepted and the property is set as sold, the selling price matches the accepted offer.

![Captura de Pantalla 2023-04-26 a la(s) 12 20 21](https://user-images.githubusercontent.com/108036643/234667652-860a33b5-a076-4775-bde3-de69e5a06cb0.png)


Regarding the labels on the form view of the property, I didn't add them before because I was following the example in the guide. However, I have now added a placeholder for the title and a label for the tags. 

![Captura de Pantalla 2023-04-26 a la(s) 12 17 59](https://user-images.githubusercontent.com/108036643/234667822-5e39288a-9035-4f4d-ae85-95b98475eac2.png)

2023-04-26 18:26 UTC, sebasdrk17 approved these changes

2023-04-26 18:27 UTC, sebasdrk17 commented
Please squash your commits, only one commit should be merged (oldest PR were merged without squash, my bad)

2023-04-26 23:20 UTC, Cindypsd commented
@sebasdrk17  Done, commits squashed

2023-04-28 18:43 UTC, sebasdrk17 approved these changes

2023-04-28 18:44 UTC, merged